name: Issue assignment

on: 
    issues:
        types: [opened]
        
        
jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: posil/auto-assign-issue@v1.0.3
              with:
                  repo-token: ${{ secrets.GITHUB.TOKEN}}
                  assignees: testesdapri
        
